package Veli.Store.PageObject;

import com.codeborne.selenide.Selectors;
import com.codeborne.selenide.SelenideElement;
import org.openqa.selenium.By;

import static com.codeborne.selenide.Selectors.*;
import static com.codeborne.selenide.Selenide.$;

import static com.codeborne.selenide.Selectors.byXpath;
import static com.codeborne.selenide.Selenide.getSelectedRadio;

public class veliwish {
    protected SelenideElement
            cookie = $(byText("ვებსაიტი იყენებს cookie ფაილებს.")),
            use = $(byText("გამოყენების პირობები")),
            accept = $(byText("ვეთანხმები")),
            carttitle = $(".header", 0),
            cartquantity = $(".fwFHuY"),
            search = $(byXpath("//*[@id=\"__next\"]/header/div[4]/div/div[2]/form/input")),
            one = $(".styled__CategoryMain-sc-1c2gm5l-11"),
            product = $(byText("პროდუქტები არ მოიძებნა")),
    //სურვილების სია,
    wishlist = $(".to-wishlist", 3),
            creataccount = $(".account"),
            avtorization_title = $(byText("ავტორიზაცია")),
            registration_title = $(byText("რეგისტრაცია")),
            title = $(byText("გაიარე ავტორიზაცია")),
            email = $(byName("email")),
            forget_password = $(".update-password"),
            password = $(byName("password")),
            pass2 = $(byName("password2")),
            login = $(".dCwCil"),
            wish = $(".to-wishlist", 3),// aq var
            action = $(".actions", 1).$(".to-wishlist", 1),
            text = $(byText("პროდუქტი დაემატა სურვილების სიაში")),
            papia = $(".eknzBd", 3),
            addcart = $("#cart-button-z"),
            texts = $(byText("ნივთი დაემატა კალათაში")),
            cart = $(byText("კალათა")),
            see = $(byText("ნახვა")),
            seecart = $(".cart", 1), // aq var
            categories = $(".active", 2),
            book = $(byText("წიგნები")),
            some_cart = $(".add-to-cart", 3), //add-to-cart
            clear = $(".clear active"),
            see_cart = $(byText("კალათის ნახვა")),
            increase = $(byXpath("//*[@id=\"card_0\"]/div[2]/div[2]/div[1]/button[2]")),
            decrease = $(byXpath("//*[@id=\"card_0\"]/div[2]/div[2]/div[1]/button[1]")),
            deleteicone = $(".delete"),
            trash = $(".delete", 1),
            remove = $(".remove", 0),
            t = $(byText("კალათიდან წაშლა")),  // ნამდვილად გსურს პროდუქტის კალათიდან წაშლა
            empty_c = $(byText("კალათა ცარიელია")),
            move = $(byText("სურვილების სიაში გადატანა")),
            path = $(byXpath("//*[@id=\"__next\"]/header/div[4]/div/div[5]/div[1]/h3")),
            mycart = $(byText("ჩემი კალათა")),
            all = $(byText("სულ :")),
            buy = $(byXpath("//*[@id=\"__next\"]/header/div[4]/div/div[5]/div[3]/div/a[2]")),
            info = $(byText("საკონტაქტო ინფორმაცია")),
            input1 = $(byName("email")),
            fullname = $(byName("fullname")),
            adpath = $(byXpath("//*[@id=\"cart-button-y\"]")),
            bagi = $(".styled__CardWrapper-sc-1dgygsi-0", 1),
            ttle = $(byText("Bagi, მაგიდის საწმენდი ტილო, \"რილუქსი\" 24x28 სმ, 1 ცალი.")),
            div = $(".styled__DetailsWrapper-sc-1uk415o-2 hSZtRI"),
            byyy = $(".dark"),
            Buy = $(".buy dark-hover"),
            btn = $(byText("ყიდვა")),
            check = $(byText("Bagi, მაგიდის საწმენდი ტილო, \"რილუქსი\" 24x28 სმ, 1 ცალი.")),
            scroling = $(".styled__DetailsWrapper-sc-1uk415o-2 hSZtRI"),
            bought = $(".buy"),
            name = $(byName("username")),
            input_input = $(".styled__Input-c2kc73-1", 2),
            phone = $(byName("phone")),
            pat = $(byXpath("//*[@id=\"__next\"]/div[2]/section/div/div[3]/div[5]/div[4]/div[1]/h3/a")),
            link = $(".eknzBd", 1),
            creat = $(".dCwCil"),
            enter = $(byText("შეიყვანე პაროლი და ანგარიში შეკვეთის დასრულებისთანავე შეიქმნება")),
            contin = $(".step-button"),
    passwordfield = $(".kMBKen"), // aq var
            scrol = $(".iOnmOh"),
    go = $(byText("შესვლა")),
            length = $(byText("პაროლი უნდა შეიცავდეს მინიმუმ 8 სიმბოლოს")),
            tx = $(byText("ინფორმაცია არავალიდურია")),
            fill = $(byText("გთხოვ, შეავსო მეილის ველი")),
            nmb = $(byText("გთხოვ, ჩაწერო მობილურის ნომერი")),
            pass_fill = $(byText("გთხოვ, შეავსო პაროლის ველი")),
            fill_repeatpass = $(byText("გაიმეორე პაროლი")),
            search_txt = $(byText("პროდუქტები არ მოიძებნა")),
            name_lastname = $(".cialdQ", 0),
            name_div = $(".styled__FilledData-sc-1yijk8q-49", 0), // 1
            mail_div = $("styled__FilledData-sc-1yijk8q-49", 1),//2
            numb_div = $("styled__FilledData-sc-1yijk8q-49", 2), //3
            mail_input = $(".cialdQ", 1),
            number_input = $(".cialdQ", 2),
            cart_title = $(byText("კალათა")),
            price = $(".price", 4),
            promo_code = $(byText("გამოიყენე ვაუჩერი")),
            products = $(byText("პროდუქტები")),
            delivery_fee = $(byText("მიტანის საფასური")),
            total_cost = $(byText("ჯამური ღირებულება")),
            close_cart = $(".btn", 2),
            sale = $(byText("ფასდაკლება")),
            safe = $(byText("გადახდის დაცული მეთოდები")),
            free_delivery = $(".text", 2),
            delivery = $(".hoixBg"),//
            address = $(".cqYOiA", 0),
            select = $(".text", 4),
            add_adress = $(".jITbRy"),
            select_time = $(byText("აირჩიე მიტანის დრო")),
    timeslot_div = $(".fbXHMV"),
          //  timeslot = $(".display", 1),
            input_class = $(".display", 1), //  .hmHHwM
            order = $(".option", 0),
            bell = $(".option", 1),
            next = $(byText("შემდეგი")),
            pay = $(byText("გადახდა")),
            recipient = $(byText("მიმღები")),
            deliver = $(byText("მიწოდება")),
            productsincart = $(byText("პროდუქტები კალათაში")),
            showdetail = $(byText("მაჩვენე დეტალურად")),
            button = $(byXpath("//*[@id=\"__next\"]/section/div/div/div[4]/div/div[1]/div/div[3]/button")),
            titleabout_pay = $(byText("გადახდა")),
            add_card = $(".pay"),
    //  your_card =
    bankcard = $(".-active"),
            card_payment = $(byXpath("//*[@id=\"cardNumber\"]")),
            add_cart = $(byText("კალათაში დამატება")),
            some_scroll = $(".hSZtRI"),
            another_scroll = $(".fhNHlw", 6),
            third_scroll = $(".characteristics"),
            back = $(byText("უკან")),
            name_input = $(".fimjls", 0),
            n_input = $(".fimjls", 1),
            nmb_input = $(".fimjls", 2),
            Vaucher = $(".soundest-form-background-image-close", 2),
            myveli = $(".header-hover", 1),
            write = $(byText("მოგვწერე")),
            wish_icone = $(".nav-item", 6),
            hello = $(byText("გამარჯობა")),
            wishdiv = $(".hovlJv"), // aq var
            wishes_title = $(byText("სურვილები")),
            product_delet = $(byText("პროდუქტი წაიშალა სურვილების სიიდან")),
            wish_scroll = $(".styled__WishlistCard-nrxmst-43 bVyiGl", 0),
            orders = $(byText("შეკვეთები")),
            mycards = $(byText("ჩემი ბარათები")),
            addresses = $(byText("მისამართები")),
            paramtrs = $(byText("პარამეტრები")),
            logout = $(byText("გამოსვლა")),
            firstadrs = $(".styled__AddressCard-nrxmst-23", 0),
            secondadrs = $(".styled__AddressCard-nrxmst-23", 1),
            edit = $(byXpath("//*[@id=\"__next\"]/section/div/div[2]/div[1]/div[3]/div[2]/button")),
            change_adrs = $(byText("შეცვლა")),
            enter_address = $(byText("შეიყვანე მისამართი")),
            changeAdres = $(byXpath("//*[@id=\"__next\"]/div[2]/div[3]/form/div[2]/label")),
            dlt_btn = $(".btn", 1), // aq mecera indexsi 1
            adress = $(byText("მისამართის დამატება")),
            ScrLL = $(".styled__ProfileContent-nrxmst-5"),
            main_addres = $(byText("აირჩიე ძირითად მისამართად")),
            sqroli = $(".gPabhr"),
            private_info = $(byText("პირადი ინფორმაცია")),
            security = $(byText("უსაფრთხოება")),
            securiti = $(byText("უსაფრთხოება")),
            passs = $(byText("პაროლი")),
            change_password = $(byText("პაროლის შეცვლა")),
            emmail = $(byText("მეილი")),
            name_and_lastname = $(byText("სახელი, გვარი")),
            changeN = $(byText("შეცვლა")),
            security_scrl = $(".IKKhk"),
            password_old = $("#old_password"),
            update_password = $(".iXMpIk"),
            new_pass = $(byText("ახალი პაროლი")),
            cancel = $(byText("გაუქმება")),
            byname = $(byName("username")),
            change_ifromation = $(byText("ინფორმაცია წარმატებით შეიცვალა")),
            mobile_numb = $(byText("მობილურის ნომერი")),
            change_numb = $(byXpath("//*[@id=\"__next\"]/section/div/div[2]/div[1]/div[4]/div[3]/div[1]/div/button")),
            detail = $(".hint", 0),
            order_detail = $(byText("შეკვეთის დეტალები")),
            purchase_time = $(byText("შეძენის თარიღი")),
            order_number = $(byText("შეკვეთის ნომერი")),
            status = $(byText("სტატუსი")),
            payment = $(byText("გადახდის მეთოდი")),
            deliverYyY = $(byText("უფასო მიტანა")),
            adrs = $(byText("მისამართი")),
            scrollinng = $(".card", 1),
            deliver_time = $(byText("მიტანის დრო")),
            purchased_product = $(byText("შეძენილი პროდუქცია")),
            repeat_purchase = $(byText("შეძენის გამეორება")),
            processing = $(byText("მუშავდება")),
            way = $(byText("გზაშია")),
            delivered = $(byText("მიტანილია")),
            returned_status = $(byText("დაბრუნებული")),
            save_address = $(byText("მისამართის შენახვა")),
            cncelbtn = $(byXpath("//*[@id=\"__next\"]/section/div/div[2]/div[1]/div[3]/form/div[6]/a")),
            last_adrs = $(".dCwFsj"),
            empty_address = $(byText("მისამართების სია ცარიელია")),
            mycard = $(byText("ჩემი ბარათები")),
            donthave_card = $(byText("შენ არ გაქვს ჯერ ბარათი დამატებული")),
            cardwill_add = $(byText("ბარათი დაემატება შენს პროფილს, როგორც კი პროდუქტს შეიძენ.")),
            sort = $(byText("დალაგება")),
            sort_price = $(".styled__SortButtons-sc-183mmht-25", 0),// იყო ეს .styled__SortButtons-sc-183mmht-25
            sort_name = $(byText("სახელი")),
            ssale = $(byText("ფასდაკლება")),
            filter = $(".styled__SortButtons-sc-183mmht-25", 1),
            filter_two = $(".styled__SortButtons-sc-183mmht-25", 0),
            napkin = $(byText("ხელსახოცი")),
            filterprice = $(byText("ფასი")),
            min = $(byXpath("//*[@id=\"__next\"]/section/div/div[2]/div[2]/div/form/div[1]/input")),
            max = $(byXpath("//*[@id=\"__next\"]/section/div/div[2]/div[2]/div/form/div[2]/input")),
            searchbtn = $(byXpath("//*[@id=\"__next\"]/section/div/div[2]/div[2]/div/form/button")),
            numberoflayers = $(byText("ფენების რაოდენობა")),
            checkboxsreplace = $(byXpath("//*[@id=\"ფენების რაოდენობა-label_0\"]")),
            colour = $(byText("ფერი")),
            colorwhite = $("#ფერი-label_1"),
            wishlist_btn = $(".wishlist-btn");
}
