package Veli.Store.PageObject;

import com.codeborne.selenide.SelenideElement;

import static com.codeborne.selenide.Selectors.*;
import static com.codeborne.selenide.Selenide.$;

public class veliavtorization {
    protected SelenideElement
            cookie = $(".styled__CookieWrapper-mh0716-12"),
         //   cookie = $(byText("ვებსაიტი იყენებს cookie ფაილებს.")),
            use = $(byText("გამოყენების პირობები")),
            accept = $(byText("ვეთანხმები")),
            creataccount = $(".account"),
            checktitle = $(byText("გაიარე ავტორიზაცია")),
            registr_number = $(".jTEdgw", 2),
            avtorization_title = $(byText("ავტორიზაცია")),
            registration_title = $(byText("რეგისტრაცია")),
            cart = $(byText("კალათა")),
            mycart = $(byText("ჩემი კალათა")),
            facebook = $(byText("შესვლა Facebook-ით")),
            input = $("#email"),
            email = $(byName("email")),
            password = $(byName("password")),
            forget_password = $(".update-password"),
            recover_pass = $(byText("პაროლის აღდგენა")),
            recovering = $(byText("პაროლის აღსადგენად, შეიყვანე რეგისტრირებული მეილი")),
            mandatory_text = $(byText("ველის შევსება სავალდებულოა")),
            login = $(".dCwCil"),
            errortitle = $(byText("გთხოვ, შეავსო მეილის ველი")),
            errormes = $(byText("გთხოვ, შეავსო პაროლის ველი")),
            repeat_password = $(byText("გაიმეორე პაროლი")),
            valmessage = $(byText("შევსებული ინფორმაცია არავალიდურია")),
            length = $(byText("პაროლი უნდა შეიცავდეს მინიმუმ 8 სიმბოლოს")),
            google = $(byText("შესვლა Google-ით")),
            some_id = $("#identifierId"),
            xpath = $(byXpath("//*[@id=\"identifierId\"]")),
    //registrat
    title = $(byText("რეგისტრაცია")),
            heading = $(".heading", 0),
            head = $(".heading", 1),
            Rmail = $(".jTEdgw", 0),// registraciis meili
            username = $("#username"),
            signup = $("#signup-password"),
            password2 = $(byName("password2")),
            enter = $(".dCwCil"), // styled__AuthPrimaryBtn-j8eqsn-2
            text = $(byText("შევსებული ინფორმაცია არავალიდურია")),
            Text = $(byText("გთხოვ, შეავსო მეილის ველი")),
    name = $(byText("გთხოვ, შეავსო სახელი და გვარი")),
            pas = $(byText("პაროლი")),
            pass = $("#signin-password"),
            send = $(byText("გაგზავნა")),
            link = $(byText("პაროლის აღდგენის ბმული გამოგზავნილია მეილზე")),
            checkmail = $(byText("მეილი არ მოვიდა?")),
            sendagain = $(byText("ხელახლა გაგზავნა")),
            err = $(byText("მეილი არ არსებობს")),
            books_category = $(byXpath("//*[@id=\"__next\"]/header/div[4]/div[2]/div/div/div[2]/button[1]")),
            fiction = $(".cover", 0),
            scroling = $(".iiucjn"),
            close = $(".close", 0),
            close_icone = $(".close", 1),
            search = $(byXpath("//*[@id=\"__next\"]/header/div[4]/div/div[2]/form/input")),
            deliver = $(byText("მიწოდება")),
            returntitle = $(byText("დაბრუნება")),
            contact = $(byText("კონტაქტი")),
            second_contact = $(byXpath("//*[@id=\"__next\"]/header/div[3]/div/button")),
            velinumber = $(byText("032 2 56 05 05")),
            chat_title = $(".noaboutme"),
    startchat = $("ჩათის დაწყება"),
            logo = $(byXpath("//*[@id=\"window-ribbon\"]/header/div/div[2]")),
            close_chat = $(".win_close sqico-larrow"),
            product = $(byText("პროდუქტები არ მოიძებნა")),
            chat_icone = $("#zsiq_float"),
            all_categories = $(".menu"),
            first_category = $(".category", 0),
            Second_category = $(".category", 1),
            third_category = $(".category", 2),
            forth_category = $(".category", 3),
            fifth_category = $(".category", 4),
            sixth_category = $(".category", 5),
            seventh_category = $(".category", 6),
            eighth_category = $(".category", 7),
            b_category = $(".sub", 2),
            some_category = $(".banner", 1),
            category_title = $(byText("3-5 წლის ბავშვებისთვის")),
            parent_one = $(".parent", 1),
            categoriestitle = $(".styled__FilterHeading-sc-1c2gm5l-5"),
            eat = $(byText("კვება")),
            care = $(byText("მოვლა")),
            accessories = $(byText("accessories")),
            Electrical_device = $(byText("ელექტრო მოწყობილობა")),
            mother = $(byText("მშობელი")),
            technic_categories = $(".hCWsqd"),
            comp_devices = $(byText("კომპიუტერული ტექნიკა")),
            leptops = $(byText("ლეპტოპები")),
            bathroom = $(byText("სააბაზანო")),
            clouds_gloves_parks = $(byText("ღრუბლები, ხელთათმანები & პარკები")),
            gloves = $(byText("ხელთათმანები"));

}